apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "gcp-broker-provider.fullname" . }}-delete
  labels:
    app: {{ include "gcp-broker-provider.name" . }}
    chart: {{ include "gcp-broker-provider.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: {{ include "gcp-broker-provider.fullname" . }}
      restartPolicy: Never
      containers:
      - name: installer
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}

        command: ["gcp-broker"]
        args: ["--action", "deprovision"]
        env:
        - name: WORKING_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLOUDSDK_CORE_PROJECT
          valueFrom:
            secretKeyRef:
              name: {{ .Values.gcpBroker.secretName }}
              key: project-name
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/secrets/sa.key"
        volumeMounts:
        - name: secrets
          mountPath: "/etc/secrets"
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: {{ .Values.gcpBroker.secretName }}
          items:
          - key: sa-key
            path: sa.key

