kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "gcp-broker-provider.fullname" . }}
  labels:
    app: {{ include "gcp-broker-provider.name" . }}
    chart: {{ include "gcp-broker-provider.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["serviceaccounts", "namespaces", "pods"]
  verbs: ["get", "patch", "create", "delete", "list"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "patch", "create", "delete"]
- apiGroups: ["extensions"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "patch", "create", "update", "delete"]
- apiGroups: ["servicecatalog.k8s.io"]
  resources: ["servicebrokers"]
  verbs: ["get","patch", "create", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "update", "delete"]

- apiGroups: [""] # required in roles created by `sc` tool
  resources: ["namespaces"]
  verbs:     ["get","list","watch"]
- apiGroups: [""] # required in roles created by `sc` tool
  resources: ["secrets"]
  verbs:     ["get","list", "watch", "create", "update", "patch", "delete"]
