apiVersion: v1
kind: Secret
metadata:
  name: {{ template "azure-auth-secret" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  redis-password: {{ randAlphaNum 10 | b64enc | quote }}
  username: {{ b64enc .Values.basicAuth.username }}
  password: {{ randAlphaNum 10 | b64enc }}
