apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-auth
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ $pass :=  randAlphaNum 10 }}
  username: {{ b64enc .Values.basicAuth.username }}
  password: {{ $pass | b64enc }}
