apiVersion: batch/v1
kind: Job
metadata:
    name: azure-service-broker-check-job
    labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    annotations:
        "helm.sh/hook": post-install,post-upgrade
        "helm.sh/hook-weight": "0"
        "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
    backoffLimit: 0
    template:
        metadata:
            annotations:
                 sidecar.istio.io/inject: "false"
        spec:
            serviceAccountName: {{ template "fullname" . }}
            restartPolicy: Never
            containers:
                - name: broker-checker
                  image: "{{ .Values.jobs.kubectlImage.repository }}:{{ .Values.jobs.kubectlImage.tag }}"
                  imagePullPolicy: {{ .Values.jobs.kubectlImage.pullPolicy }}
                  command: ["/bin/sh","-c"]
                  args:
                    - |
                      SECRET_NAME=$(kubectl get secret -n {{ .Release.Namespace }} azure-broker-data -o jsonpath="{.metadata.name}")
                      if [[ "$SECRET_NAME" == "azure-broker-data" ]] ;
                        then
                          echo "Success! Secret is present.";
                        else
                          echo "Failure! Secret 'azure-broker-data' is not present";
                          exit 1;
                      fi

                      success=false;
                      i=1;
                      limit=180;
                      while [ "$i" -le "$limit" ];
                      do
                          BROKER_TYPE=$(kubectl get servicebroker -n {{ .Release.Namespace }} {{ include "fullname" . }} -o jsonpath="{.status.conditions[0].type}")
                          BROKER_STATUS=$(kubectl get servicebroker -n {{ .Release.Namespace }} {{ include "fullname" . }} -o jsonpath="{.status.conditions[0].status}")
                          if [[ "$BROKER_TYPE" == "Ready" ]] && [[ "$BROKER_STATUS" == "True" ]];
                            then
                              echo "ServiesBroker is ready. Job is done.";
                              success=true;
                              break;
                            else
                              echo "Check $i/$limit - ServiceBroker is not ready, wait...";
                              sleep 5;
                          fi
                        i=$(( i + 1 ))
                      done;
                      if [ "$success" = false ] ;
                      then
                        echo "ServiesBroker is not ready. Timeout reached";
                        exit 1;
                      fi
---
apiVersion: batch/v1
kind: Job
metadata:
    name: azure-service-broker-docu-checker
    labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    annotations:
        "helm.sh/hook": post-install,post-upgrade
        "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
    template:
        metadata:
            annotations:
                sidecar.istio.io/inject: "false"
        spec:
            serviceAccountName: {{ include "fullname" . }}-docu-checker
            restartPolicy: Never
            containers:
                - name: docu-checker
                  image: eu.gcr.io/kyma-project/test-infra/alpine-kubectl:v20190325-ff66a3a
                  imagePullPolicy: IfNotPresent
                  command: ["/bin/sh","-c"]
                  args:
                      - |
                          while true
                          do
                            echo "Get list of not ready DocsTopic:"
                            lines=$(kubectl get DocsTopic -l chart=${LABEL_CHART} -l release=${LABEL_RELEASE} -n ${NS} \
                              --no-headers -o custom-columns=name:.metadata.name,phase:.status.phase | awk '$2!="Ready"' | wc -l)

                            echo "Got ${lines} not ready Docs Topic"

                            if [[ "${lines}" -eq "0" ]];
                            then
                                echo "Every DocsTopic is processed. Completed."
                                exit 0
                            fi
                            sleep 3
                            echo "----"
                          done


                  env:
                      - name: LABEL_CHART
                        value: {{ .Chart.Name }}-{{ .Chart.Version }}
                      - name: LABEL_RELEASE
                        value: {{ .Release.Name }}
                      - name: NS
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.namespace
