name: aws-service-broker
version: 0.0.1
id: 0a54e829-c352-4978-9291-c37f779e1900
description: "Extends the Service Catalog with Amazon Web Services"
displayName:  AWS Broker

tags: aws, amazon, broker
providerDisplayName: Amazon
longDescription: The AWS Service Broker allows native AWS services to be exposed directly through application platforms that implement the Open Service Broker API, and provides simple integration of AWS Services directly within the application platform.
documentationURL: https://github.com/awslabs/aws-servicebroker/blob/master/docs/README.md
imageURL: https://a0.awsstatic.com/libra-css/images/logos/aws_logo_smile_1200x630.png
bindable: false
provisionOnlyOnce: true
