apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ template "fullname" . }}-docu-checker
    labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
