apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-credentials
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  accesskeyid: {{ b64enc .Values.aws.accesskeyid }}
  secretkey: {{ b64enc .Values.aws.secretkey }}
