docs:
  - template:
      displayName: "Documentation for GCP Service Broker"
      description: "Overall documentation"
      sources:
        - type: markdown
          name: markdown-files
          mode: package
          filter: docs/broker
