kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
    name: {{ include "fullname" . | trunc 60 }}-dc
    labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
subjects:
    - kind: ServiceAccount
      name: {{ include "fullname" . | trunc 60 }}-dc
      namespace: {{ .Release.Namespace }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: {{ include "fullname" . | trunc 60 }}-dc
