kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
    name: {{ include "fullname" . | trunc 60 }}-dc
    labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
rules:
    - apiGroups: ["cms.kyma-project.io"]
      resources: ["docstopics"]
      verbs: ["list"]
