apiVersion: batch/v1
kind: Job
metadata:
    name: {{ template "gcp-service-broker.fullname" . }}
    labels:
        app: {{ template "gcp-service-broker.fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    annotations:
        "helm.sh/hook": post-install,post-upgrade
        "helm.sh/hook-weight": "5"
        "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
    backoffLimit: 0
    template:
        metadata:
            annotations:
                 sidecar.istio.io/inject: "false"
        spec:
            serviceAccountName: {{ template "gcp-service-broker.fullname" . }}
            restartPolicy: Never
            containers:
                - name: broker-checker
                  image: "{{ .Values.jobs.kubectlImage.repository }}:{{ .Values.jobs.kubectlImage.tag }}"
                  imagePullPolicy: {{ .Values.jobs.kubectlImage.pullPolicy }}
                  command: ["/bin/sh","-c"]
                  args:
                    - |
                      success=false;
                      i=1;
                      limit=180;
                      while [ "$i" -le "$limit" ];
                      do
                          BROKER_TYPE=$(kubectl get servicebroker -n {{ .Release.Namespace }} {{ include "gcp-service-broker.fullname" . }} -o jsonpath="{.status.conditions[0].type}")
                          BROKER_STATUS=$(kubectl get servicebroker -n {{ .Release.Namespace }} {{ include "gcp-service-broker.fullname" . }} -o jsonpath="{.status.conditions[0].status}")
                          if [[ "$BROKER_TYPE" == "Ready" ]] && [[ "$BROKER_STATUS" == "True" ]];
                            then
                              echo "ServiesBroker is ready. Job is done.";
                              success=true;
                              break;
                            else
                              echo "Check $i/$limit - ServiceBroker is not ready, wait...";
                              sleep 5;
                          fi
                        i=$(( i + 1 ))
                      done;
                      if [ "$success" = false ] ;
                      then
                        echo "ServiesBroker is not ready. Timeout reached";
                        exit 1;
                      fi
