name: gcp-service-broker
version: 0.0.2
id: aff0f62c-a988-406f-a950-348473743071
description: "Extends the Service Catalog with Google Cloud Platform services"
displayName:  Google Cloud Platform Service Broker

tags: gcp, google, broker
providerDisplayName: "Google Cloud Platform"
longDescription: Google Cloud Platform (GCP) Service Broker is an implementation of the open-source Open Service Broker (OSB) API hosted on GCP
documentationURL: https://cloud.google.com/kubernetes-engine/docs/concepts/google-cloud-platform-service-broker
imageURL: https://cloud.google.com/_static/images/cloud/icons/favicons/onecloud/apple-icon.png
bindable: false
provisionOnlyOnce: true
